export const CAMERA_DETECTION_CONTRACT_VERSION="5.0.0-phase5";
export const CAMERA_DETECTION_TYPES=["motion","person","vehicle","animal","object","line_crossing","zone_intrusion","occupancy","tamper","smoke","fire","unknown"] as const;
export type CameraDetectionType=typeof CAMERA_DETECTION_TYPES[number];
export type CameraBoundingBox={x:number;y:number;width:number;height:number};
export type CameraDetection={id:string;cameraId:string;estateId:string;homeId?:string|null;eventId?:string|null;mediaId?:string|null;type:CameraDetectionType;observedAt:string;confidence?:number|null;boundingBox?:CameraBoundingBox|null;zoneId?:string|null;trackingId?:string|null;attributes:Record<string,string|number|boolean|null>;provider:string;model?:string|null;modelVersion?:string|null;createdAt:string};
export type CameraDetectionZone={id:string;cameraId:string;name:string;kind:"region"|"line";geometry:{x:number;y:number}[];enabled:boolean;detectionTypes:CameraDetectionType[];minimumConfidence?:number|null;restricted:boolean};
const text=(v:unknown)=>String(v??"").trim(),num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):null,date=(v:unknown)=>{const s=text(v);return s&&Number.isFinite(Date.parse(s))?s:null};
export function normalizeDetectionType(v:unknown):CameraDetectionType{const s=text(v).toLowerCase().replace(/[\s-]+/g,"_");if(/human/.test(s))return"person";if(/car|truck|motor|bike/.test(s))return"vehicle";if(/movement|suspicious_motion/.test(s))return"motion";if(/intrusion/.test(s))return"zone_intrusion";if(/line/.test(s))return"line_crossing";if(/tamper|obstruct/.test(s))return"tamper";return(CAMERA_DETECTION_TYPES as readonly string[]).includes(s)?s as CameraDetectionType:"unknown"}
export function normalizeBoundingBox(raw:any):CameraBoundingBox|null{const b=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw:Array.isArray(raw)&&raw.length===4?{x:raw[0],y:raw[1],width:raw[2],height:raw[3]}:{};const x=num(b.x),y=num(b.y),width=num(b.width??b.w),height=num(b.height??b.h);if(x===null||y===null||width===null||height===null||x<0||y<0||width<0||height<0||x>1||y>1||x+width>1||y+height>1)return null;return{x,y,width,height}}
function safeAttributes(raw:any){const out:Record<string,string|number|boolean|null>={};if(!raw||typeof raw!=="object"||Array.isArray(raw))return out;for(const [key,value] of Object.entries(raw).slice(0,24)){if(!/^[a-zA-Z][a-zA-Z0-9_]{0,47}$/.test(key)||["url","token","secret","password","credential","image","tensor"].some(x=>key.toLowerCase().includes(x)))continue;if(value===null||typeof value==="boolean"||typeof value==="number"&&Number.isFinite(value)||typeof value==="string"&&value.length<=160)out[key]=value as any}return out}
export function normalizeCameraDetection(raw:any):CameraDetection{return{id:text(raw?.id),cameraId:text(raw?.cameraId??raw?.camera_id),estateId:text(raw?.estateId??raw?.estate_id),homeId:text(raw?.homeId??raw?.home_id)||null,eventId:text(raw?.eventId??raw?.event_id)||null,mediaId:text(raw?.mediaId??raw?.media_id)||null,type:normalizeDetectionType(raw?.type??raw?.detection_type),observedAt:date(raw?.observedAt??raw?.observed_at)||new Date(0).toISOString(),confidence:num(raw?.confidence),boundingBox:normalizeBoundingBox(raw?.boundingBox??raw?.bounding_box),zoneId:text(raw?.zoneId??raw?.visual_zone_id)||null,trackingId:text(raw?.trackingId??raw?.tracking_id)||null,attributes:safeAttributes(raw?.attributes),provider:text(raw?.provider)||"unknown",model:text(raw?.model)||null,modelVersion:text(raw?.modelVersion??raw?.model_version)||null,createdAt:date(raw?.createdAt??raw?.created_at)||new Date(0).toISOString()}}
export type CameraDetectionTransport={get(path:string,options?:{params?:Record<string,unknown>}):Promise<{data:any}>};
export function createCameraDetectionReadClient(transport:CameraDetectionTransport){const read=(data:any)=>({items:(data?.items||[]).map(normalizeCameraDetection),nextCursor:data?.nextCursor||null});return{async getCameraDetections(cameraId:string,options?:{start?:string;end?:string;type?:CameraDetectionType;zoneId?:string;minimumConfidence?:number;limit?:number;cursor?:string}){return read((await transport.get(`/cameras/${encodeURIComponent(cameraId)}/detections`,{params:options as any})).data)},async getCameraEventDetections(eventId:string){return read((await transport.get(`/cameras/events/${encodeURIComponent(eventId)}/detections`)).data)}}}
