export const CAMERA_CORE_VERSION = "2.0.0-phase2";
export type CameraScope="facility"|"home"|"office"|"unknown"; export type CameraRuntimeState="online"|"degraded"|"offline"|"unknown"; export type CapabilityAvailability="available"|"configured"|"unavailable"|"unknown";
export type CameraCapability={availability:CapabilityAvailability;source?:string|null}; export type CameraCapabilities={liveView:CameraCapability;playback:CameraCapability;snapshots:CameraCapability;audio:CameraCapability;ptz:CameraCapability;motionDetection:CameraCapability;personDetection:CameraCapability;vehicleDetection:CameraCapability;lineCrossing:CameraCapability;zoneIntrusion:CameraCapability;faceDetection:CameraCapability;faceRecognition:CameraCapability;anpr:CameraCapability;recording:CameraCapability};
export type CameraHealth={online:boolean;status:string;streamStatus?:string|null;lastSeenAt?:string|null;lastHealthAt?:string|null;lastSuccessAt?:string|null;lastFailureAt?:string|null;latencyMs?:number|null;reconnectCount?:number|null;providerError?:string|null;frameFreshnessAt?:string|null};
export type Camera={id:string;scope:CameraScope;estateId?:string|null;buildingId?:string|null;homeId?:string|null;zoneId?:string|null;name:string;reference?:string|null;location?:string|null;status:string;streamStatus?:string|null;provider?:string|null;edgeNodeId?:string|null;capabilities:CameraCapabilities;health?:CameraHealth|null;runtimeState:CameraRuntimeState;createdAt?:string|null;updatedAt?:string|null};
export type CameraMediaReference={kind:"snapshot"|"clip"|"recording";url?:string;trust:"oyi_authorized"|"legacy_external";expiresAt?:string|null;capturedAt?:string|null};
export type CameraDetection={id?:string;type:string;confidence?:number|null;label?:string|null;zone?:string|null;occurredAt?:string|null;boundingBox?:{x:number;y:number;width:number;height:number}|null;attributes?:Record<string,unknown>};
export type CameraEvent={id:string;cameraId:string;type:string;severity:string;confidence?:number|null;createdAt:string;sourceTimestamp?:string|null;metadata:Record<string,unknown>;snapshot?:CameraMediaReference|null;clip?:CameraMediaReference|null;detections:CameraDetection[]};
export type CameraPlaybackSession={cameraId:string;protocol:"hls";url:string;expiresAt?:string|null;sessionId?:string|null;rewindSeconds?:number|null}; export type CameraContext={scope:"facility";estateId:string}|{scope:"home";homeId:string}; export type CameraOyiContext={type:"camera";id:string;name:string;scope:CameraScope;location?:string|null;estateId?:string|null;homeId?:string|null;status:CameraRuntimeState};
const t=(v:unknown,f="")=>String(v??f).trim(), nt=(v:unknown)=>t(v)||null, rec=(v:unknown):Record<string,any>=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,any>:{}, num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):null, dt=(v:unknown)=>{const x=nt(v);return x&&Number.isFinite(Date.parse(x))?x:null}, secret=new Set(["password","pass","secret","token","username","rtsp_url","edge_hls_url","hls_url","credential_ref"]), safe=(v:unknown):any=>Array.isArray(v)?v.map(safe):v&&typeof v==="object"?Object.fromEntries(Object.entries(v as Record<string,unknown>).filter(([k])=>!secret.has(k.toLowerCase())).map(([k,x])=>[k,safe(x)])):v, media=(v:unknown)=>{const x=nt(v);if(!x)return null;try{const u=new URL(x);const h=u.hostname.toLowerCase();if(!["http:","https:"].includes(u.protocol)||h==="localhost"||h==="::1"||/^(127\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.)/.test(h)||h.endsWith(".local"))return null;return x}catch{return null}};
const cap=(v:unknown):CameraCapability=>{if(v&&typeof v==="object"){const x=t((v as any).availability).toLowerCase();if(["available","configured","unavailable","unknown"].includes(x))return{availability:x as CapabilityAvailability,source:nt((v as any).source)}}if(v===true)return{availability:"available",source:"backend"};if(v===false)return{availability:"unavailable",source:"backend"};return{availability:"unknown"}};
const capKeys:(keyof CameraCapabilities)[]=["liveView","playback","snapshots","audio","ptz","motionDetection","personDetection","vehicleDetection","lineCrossing","zoneIntrusion","faceDetection","faceRecognition","anpr","recording"];
export function normalizeCameraCapabilities(raw:unknown){const s=rec(raw),o:any={};for(const k of capKeys)o[k]=cap(s[k]??s[k.replace(/[A-Z]/g,m=>`_${m.toLowerCase()}`)]);return o as CameraCapabilities}
export function normalizeCameraHealth(raw:unknown):CameraHealth|null{const v=rec(raw);if(!Object.keys(v).length)return null;return{online:v.online===true,status:t(v.status,"unknown"),streamStatus:nt(v.streamStatus??v.stream_status),lastSeenAt:dt(v.lastSeenAt??v.last_seen_at),lastHealthAt:dt(v.lastHealthAt??v.last_health_at),lastSuccessAt:dt(v.lastSuccessAt??v.last_success_at),lastFailureAt:dt(v.lastFailureAt??v.last_failure_at),latencyMs:num(v.latencyMs??v.latency_ms),reconnectCount:num(v.reconnectCount??v.reconnect_count),providerError:nt(v.providerError??v.provider_error),frameFreshnessAt:dt(v.frameFreshnessAt??v.frame_freshness_at)}}
export function cameraRuntimeState(c:Pick<Camera,"status"|"streamStatus"|"health">):CameraRuntimeState{const vs=[c.streamStatus,c.health?.streamStatus,c.health?.status,c.status].map(v=>t(v).toLowerCase()).filter(Boolean);if(vs.some(v=>["offline","failed","error","unreachable"].includes(v)))return"offline";if(c.health?.providerError||vs.some(v=>["degraded","warning","reconnecting"].includes(v)))return"degraded";if(c.health?.online===true&&vs.some(v=>["online","active","healthy","ok","ready"].includes(v)))return"online";return"unknown"}
export function normalizeCamera(raw:unknown):Camera{const v=rec(raw),m=rec(v.metadata),sr=t(v.scope??v.privacy_scope??m.privacy_scope).toLowerCase(),scope:CameraScope=["facility","home","office"].includes(sr)?sr as CameraScope:"unknown",health=normalizeCameraHealth(v.health),b={id:t(v.id),scope,estateId:nt(v.estateId??v.estate_id),buildingId:nt(v.buildingId??v.building_id??m.building_id),homeId:nt(v.homeId??v.home_id??m.home_id),zoneId:nt(v.zoneId??v.zone_id),name:t(v.name,"Camera"),reference:nt(v.reference??v.camera_id),location:nt(v.location),status:t(v.status,"unknown"),streamStatus:nt(v.streamStatus??v.stream_status),provider:nt(v.provider),edgeNodeId:nt(v.edgeNodeId??v.edge_node_id),capabilities:normalizeCameraCapabilities(v.capabilities),health,createdAt:dt(v.createdAt??v.created_at),updatedAt:dt(v.updatedAt??v.updated_at)};return{...b,runtimeState:cameraRuntimeState(b)}}
export const isCameraOnline=(c:Camera)=>c.runtimeState==="online";export const isCameraStreamHealthy=(c:Camera)=>c.runtimeState==="online"&&!c.health?.providerError;export const getCameraHealthLabel=(c:Camera)=>c.runtimeState;export const getCameraLastActivity=(c:Camera)=>c.health?.frameFreshnessAt||c.health?.lastSuccessAt||c.health?.lastSeenAt||null;
export function extractCameraDetections(raw:unknown):CameraDetection[]{const e=rec(raw),m=rec(e.metadata),xs=Array.isArray(e.detections)?e.detections:Array.isArray(m.detections)?m.detections:[];return xs.slice(0,100).map((i:any)=>{const b=rec(i.boundingBox??i.bounding_box??i.box);return{id:nt(i.id)||undefined,type:t(i.type??i.event_type??i.class,"unknown"),confidence:num(i.confidence),label:nt(i.label),zone:nt(i.zone),occurredAt:dt(i.occurredAt??i.occurred_at),boundingBox:[b.x,b.y,b.width,b.height].every(x=>Number.isFinite(Number(x)))?{x:Number(b.x),y:Number(b.y),width:Number(b.width),height:Number(b.height)}:null,attributes:rec(i.attributes)}})}
export const getCameraEventOccurrenceTime=(e:Pick<CameraEvent,"sourceTimestamp"|"createdAt">)=>dt(e.sourceTimestamp)||e.createdAt;
export function normalizeCameraEvent(raw:unknown):CameraEvent{const v=rec(raw),base=safe(rec(v.metadata)),m=nt(v.message)?{...base,message:nt(v.message)}:base,createdAt=dt(v.createdAt??v.created_at)||new Date(0).toISOString(),sourceTimestamp=dt(v.sourceTimestamp??v.source_timestamp),u=media(v.snapshot?.url??v.snapshot_url),snapshot=u?{kind:"snapshot" as const,url:u,trust:"legacy_external" as const,capturedAt:sourceTimestamp||createdAt}:null;return{id:t(v.id),cameraId:t(v.cameraId??v.camera_id),type:t(v.type??v.event_type,"unknown"),severity:t(v.severity??m.severity,"unknown"),confidence:num(v.confidence),createdAt,sourceTimestamp,metadata:m,snapshot,clip:null,detections:extractCameraDetections(v)}}
export function normalizePlaybackSession(raw:unknown,fallback=""):CameraPlaybackSession{const v=rec(raw),p=t(v.protocol??v.playback_type??v.type,"hls").toLowerCase(),url=t(v.url??v.hls_url);if(p!=="hls"||!url)throw new Error("Camera playback is unavailable");return{cameraId:t(v.cameraId??v.camera_id,fallback),protocol:"hls",url,expiresAt:dt(v.expiresAt??v.expires_at),sessionId:nt(v.sessionId??v.session_id),rewindSeconds:num(v.rewindSeconds??v.rewind)}}
export const serializeCameraOyiContext=(c:Camera):CameraOyiContext=>({type:"camera",id:c.id,name:c.name,scope:c.scope,location:c.location,estateId:c.estateId,homeId:c.homeId,status:c.runtimeState});
export type CameraTransport={get(path:string,options?:{params?:Record<string,unknown>}):Promise<{data:any}>}; export function createCameraReadClient(x:CameraTransport){return{async listCameras(c:CameraContext){const p=c.scope==="home"?`/cameras/home/${encodeURIComponent(c.homeId)}`:`/cameras/estate/${encodeURIComponent(c.estateId)}`,r=await x.get(p);return(r.data?.items||[]).map(normalizeCamera)},async getCameraEvents(id:string,o?:{limit?:number;sinceMinutes?:number}){const r=await x.get(`/cameras/${encodeURIComponent(id)}/events`,{params:{limit:o?.limit??50,sinceMinutes:o?.sinceMinutes??1440}});return(r.data?.events||[]).map(normalizeCameraEvent)},async createPlaybackSession(id:string,o?:{rewindSeconds?:number}){const rewind=Math.max(0,Math.floor(o?.rewindSeconds||0)),r=await x.get(`/cameras/${encodeURIComponent(id)}/playback`,{params:{rewind}});return normalizePlaybackSession(r.data,id)}}}
export type CameraReadClient=ReturnType<typeof createCameraReadClient>;
export type CameraSubscription=()=>void; export type CameraRealtimeAdapter={subscribeToCameraEvents(cameraId:string,onEvent:(event:CameraEvent)=>void):CameraSubscription;subscribeToCameraHealth(cameraId:string,onHealth:(health:CameraHealth)=>void):CameraSubscription};
